import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
test('filtros: acentos, palabras, condición, orden, URL y restablecimiento',async()=>{
 const nodes={};
 const element=(value='')=>({value,hidden:false,dataset:{},handlers:{},addEventListener(k,fn){this.handlers[k]=fn},focus(){this.focused=true},options:[]});
 for(const id of ['.filters','#search','#category','#condition','#sort','#product-grid','#empty-state','#result-count','#reset-filters'])nodes[id]=element();
 const items=[['Consola edición Slim','Nuevo','200'],['Consola Pro','Usado','100'],['Consola edición Slim','Usado','']].map(([name,condition,price])=>({...element(),dataset:{name,condition,price,category:'consolas'}}));
 nodes['#product-grid'].querySelectorAll=()=>items;
 let order=[...items];
 nodes['#product-grid'].append=item=>{order=order.filter(x=>x!==item);order.push(item)};
 nodes['#category'].options=['','consolas'].map(value=>({value}));
 nodes['#condition'].options=['','Nuevo','Usado'].map(value=>({value}));
 nodes['#sort'].options=['featured','price-asc','price-desc','name'].map(value=>({value}));
 nodes['.filters'].reset=()=>{};
 let url;
 const context={document:{documentElement:{classList:{add(){}}},querySelector:s=>nodes[s]||null,querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener(){}},location:{search:'',pathname:'/',hash:'#productos'},history:{replaceState(a,b,c){url=c}},URLSearchParams,setTimeout:fn=>fn(),clearTimeout(){}};
 vm.runInNewContext(await readFile('assets/app.js','utf8'),context);
 assert.equal(nodes['#result-count'].textContent,'3 productos');
 nodes['#search'].value='SLIM edicion';nodes['#search'].handlers.input();
 assert.equal(nodes['#result-count'].textContent,'2 productos');
 nodes['#condition'].value='Usado';nodes['#condition'].handlers.change();
 assert.equal(nodes['#result-count'].textContent,'1 producto');assert.ok(url.includes('condicion=Usado'));
 nodes['#reset-filters'].handlers.click();assert.equal(nodes['#result-count'].textContent,'3 productos');assert.ok(nodes['#search'].focused);
 nodes['#sort'].value='price-asc';nodes['#sort'].handlers.change();assert.deepEqual(order,[items[1],items[0],items[2]]);
 nodes['#sort'].value='featured';nodes['#sort'].handlers.change();assert.deepEqual(order,items);
 nodes['#search'].value='sin coincidencias';nodes['#search'].handlers.input();assert.equal(nodes['#empty-state'].hidden,false);
});
