import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {validateStore,escapeHTML as e,priceLabel,whatsappURL,CONDITIONS} from './catalog.mjs';
const store=validateStore(JSON.parse(await readFile('data/store.json','utf8')));
const written=[];
const placeholder='<span class="image-placeholder">Imagen próximamente</span>';
for(const p of store.products) if(p.image?.startsWith('/')) await readFile('.'+p.image);

async function save(path, content){await mkdir(path.includes('/')?path.slice(0,path.lastIndexOf('/')):'.',{recursive:true});await writeFile(path,content);written.push(path);}
const icon=(type,cls='')=>'<svg class="'+cls+'" aria-hidden="true"><use href="/assets/icons.svg#'+type+'"></use></svg>';
const wa=message=>whatsappURL(store.whatsapp,message);
const contact=(label='Consultar por WhatsApp',message='Hola FOX GAMER, quiero información sobre productos, pagos y envíos.',cls='button')=>wa(message)?'<a class="'+cls+'" href="'+e(wa(message))+'" target="_blank" rel="noopener noreferrer" aria-label="'+e(label)+' (abre WhatsApp en otra pestaña)">'+icon('chat')+e(label)+'</a>':'<a class="'+cls+'" href="/#contacto">'+icon('chat')+'Información de contacto</a>';
const categoryCards=store.categories.map(c=>'<a class="category-card" href="/categorias/'+c.slug+'/"><span class="category-art '+c.slug+'">'+(c.image?'<img src="'+e(c.image)+'" alt="" width="640" height="640" loading="lazy" decoding="async">':icon(c.icon))+'</span><span class="category-name">'+e(c.name)+icon('arrow')+'</span><span class="category-description">'+e(c.description)+'</span></a>').join('');
const availability={available:'Disponible',inquiry:'Consultar disponibilidad',soldout:'Agotado'};
function card(p){return '<article class="product-card" data-product data-name="'+e([p.name,p.brand,p.description].join(' '))+'" data-category="'+p.category+'" data-condition="'+e(p.condition)+'" data-price="'+(p.price??'')+'"><a href="/productos/'+p.slug+'/"><div class="product-image">'+(p.image?'<img src="'+e(p.image)+'" alt="'+e(p.name)+'" width="640" height="480" loading="lazy" decoding="async">':placeholder)+'<span class="badge">'+e(p.condition)+'</span></div><div class="product-info"><span class="eyebrow">'+e(p.brand||p.category)+'</span><h3>'+e(p.name)+'</h3><p>'+availability[p.availability]+'</p><strong>'+priceLabel(p)+'</strong><span class="detail-link">Ver producto '+icon('arrow')+'</span></div></a>'+ (p.availability==='soldout'?'':contact('Consultar por WhatsApp','Hola FOX GAMER, quiero consultar '+p.name+' ('+p.condition+'). '+store.url+'/productos/'+p.slug+'/','button secondary card-contact'))+'</article>';}
function catalog(category){
const conditionOrder={Nuevo:0,Exhibición:1,Usado:2}; const featuredOrder={'PlayStation 4 Pro 1 Tera':0,'PlayStation 4 Fat 500GB':1,'PlayStation 5 Slim 1 Tera':2,'PlayStation 5 Fat 825GB':3,'Xbox Series S 512 GB':4,'Xbox Series S 1 TB':5,'Xbox Series X Disco 1 Tera':6}; const products=store.products.filter(p=>!category||p.category===category).sort((a,b)=>(featuredOrder[a.name]??100)-(featuredOrder[b.name]??100) || a.name.localeCompare(b.name,'es') || conditionOrder[a.condition]-conditionOrder[b.condition]);
return '<section class="section wrap" id="productos" aria-labelledby="catalog-title"><div class="section-top"><div><p class="eyebrow">ENCUENTRA TU PRÓXIMO FAVORITO</p><h2 id="catalog-title">'+(category?'Catálogo de '+e(store.categories.find(c=>c.slug===category).name):'Explora el catálogo')+'</h2></div><span class="small">Precios en pesos colombianos · COP</span></div><form class="filters" role="search" action="#productos"><label class="search-label">Buscar productos<span>'+icon('search')+'<input id="search" name="q" type="search" placeholder="Consola, juego, marca…" maxlength="100" autocomplete="off"></span></label><label>Categoría<select id="category" name="categoria"><option value="">Todas las categorías</option>'+store.categories.map(c=>'<option value="'+c.slug+'" '+(category===c.slug?'selected':'')+'>'+e(c.name)+'</option>').join('')+'</select></label><label>Condición<select id="condition" name="condicion"><option value="">Todas las condiciones</option>'+CONDITIONS.map(c=>'<option>'+c+'</option>').join('')+'</select></label><label>Ordenar<select id="sort" name="orden"><option value="featured">Destacados</option><option value="price-asc">Menor precio</option><option value="price-desc">Mayor precio</option><option value="name">Nombre A–Z</option></select></label><button class="button filter-submit" type="submit">Buscar</button></form><p id="result-count" class="small" role="status" aria-live="polite">'+products.length+' productos</p><div class="product-grid" id="product-grid">'+products.map(card).join('')+'</div><div class="empty-state" id="empty-state" '+(products.length?'hidden':'')+'>'+icon('search')+'<h3>'+(products.length?'No encontramos productos con esos filtros':'Estamos preparando el catálogo')+'</h3><p>'+(products.length?'Prueba otra búsqueda o cambia la condición.':'Publicaremos cada producto con su precio, disponibilidad y condición verificados.')+'</p><button class="button secondary" id="reset-filters" type="button">Limpiar filtros</button></div><noscript><p>Los productos y sus fichas están disponibles sin JavaScript. Para usar los filtros, activa JavaScript o navega por las categorías.</p></noscript></section>';
}

function gallery(category){
 const photos=(store.gallery||[]).filter(p=>!category||p.category===category).map(p=>({...p,title:'Fotografía de la tienda · '+(p.source || 'FOX GAMER')}));
 if(!photos.length)return '';
 const shown=category?photos:photos.filter((p,i)=>[0,3,4,8,11,16,18,21].includes(i));
 return '<section class="section wrap photo-gallery" aria-labelledby="gallery-title"><div class="section-top"><div><p class="eyebrow">FOTOGRAFÍAS DE NUESTRA TIENDA</p><h2 id="gallery-title">El universo FOX GAMER, de cerca.</h2></div><span class="small">'+shown.length+' fotografías</span></div><p class="gallery-intro">Explora nuestras fotografías. Consulta precio, disponibilidad y condición de cada unidad antes de comprar.</p><div class="photo-grid">'+shown.map(p=>'<figure class="photo-card"><a href="'+e(p.large)+'" data-gallery-image aria-label="Ampliar fotografía: '+e(p.title)+'"><img src="'+e(p.image)+'" alt="'+e(p.title)+' en FOX GAMER" width="640" height="640" loading="lazy" decoding="async"><span class="photo-zoom" aria-hidden="true">'+icon('search')+'</span></a><figcaption><h3>'+e(p.title)+'</h3><p>Precio y condición por confirmar</p></figcaption></figure>').join('')+'</div></section><dialog id="photo-dialog" aria-labelledby="photo-dialog-title"><button type="button" class="dialog-close" aria-label="Cerrar fotografía">Cerrar ×</button><img id="photo-dialog-image" alt=""><h2 id="photo-dialog-title">Fotografía de FOX GAMER</h2></dialog>';
}

const payments='<section class="section wrap" id="pagos"><div class="section-top"><div><p class="eyebrow">A TU MANERA</p><h2>Opciones para tu compra</h2></div><p class="muted">Confirma las condiciones antes de pagar.</p></div><div class="info-grid"><article class="info-card">'+icon('wallet')+'<h3>Transferencia y efectivo</h3><p>Consulta los datos y las condiciones de pago con FOX GAMER al confirmar tu pedido.</p></article><article class="info-card">'+icon('card')+'<h3>Crédito y financiación</h3><p>Crédito directo y opciones de financiación sujetos a aprobación. Solicita plazos, cuotas y costo total antes de decidir.</p></article><article class="info-card">'+icon('truck')+'<h3>Envíos en Colombia</h3><p>Envíos nacionales con seguimiento. Confirma cobertura, costo y tiempo estimado según tu destino.</p></article></div></section>';
const conditions='<section class="condition-section" id="condiciones"><div class="wrap condition-layout"><div><p class="eyebrow">CLARIDAD EN CADA COMPRA</p><h2>El estado importa.<br>Siempre a la vista.</h2><p class="muted">La condición se indica en cada producto. Revisa también los detalles de la unidad, los accesorios incluidos y su garantía.</p></div><div class="condition-list"><article><span class="condition-dot new"></span><div><h3>Nuevo</h3><p>Producto sin uso. El empaque, los accesorios y la garantía se detallan en la ficha.</p></div></article><article><span class="condition-dot used"></span><div><h3>Usado</h3><p>Producto con uso previo. Consulta las señales de uso y el estado específico de la unidad.</p></div></article><article><span class="condition-dot display"></span><div><h3>Exhibición</h3><p>Unidad utilizada para exposición o demostración. Revisa su estado y contenido incluido.</p></div></article></div></div></section>';
const socialLinks=Object.entries(store.socials||{}).filter(([name,url])=>['instagram','facebook'].includes(name)&&url).map(([name,url])=>'<a href="'+e(url)+'" target="_blank" rel="noopener noreferrer">'+(name==='instagram'?'Instagram':'Facebook')+'</a>').join('');
const catalogLink=store.whatsappCatalog?'<a class="button secondary" href="'+e(store.whatsappCatalog)+'" target="_blank" rel="noopener noreferrer">Ver catálogo en WhatsApp '+icon('arrow')+'</a>':'';
const contactSection='<section class="wrap section" id="contacto"><div class="contact-panel"><div><p class="eyebrow">HABLEMOS DE TU PRÓXIMO EQUIPO</p><h2>Te ayudamos a elegir.</h2><p>Resuelve tus dudas sobre disponibilidad, estado, pagos y envíos antes de comprar.</p>'+(store.whatsapp?'':'<p class="contact-pending">El canal de WhatsApp se publicará aquí cuando esté confirmado.</p>')+'</div>'+'<div class="contact-actions">'+(store.whatsapp?contact():'<a class="button" href="/#productos">Explorar categorías '+icon('arrow')+'</a>')+catalogLink+(store.whatsapp?'<span class="small">WhatsApp: +'+e(store.whatsapp)+'</span>':'')+'</div>'+'</div></section>';
function page(title,description,path,body,extra=''){
const canonical=store.url+path;
const product=store.products.find(p=>path==='/productos/'+p.slug+'/');
const shareImage=product?.image?new URL(product.image,store.url).href:store.url+'/assets/brand/fox-gamer-original.jpg';
return '<!doctype html>\n<html lang="es-CO"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(title)+'</title><meta name="description" content="'+e(description)+'"><meta name="theme-color" content="#101117"><link rel="canonical" href="'+canonical+'"><meta property="og:type" content="'+(path.startsWith('/productos/')?'product':'website')+'"><meta property="og:title" content="'+e(title)+'"><meta property="og:description" content="'+e(description)+'"><meta property="og:url" content="'+canonical+'"><meta property="og:site_name" content="FOX GAMER"><meta property="og:locale" content="es_CO"><meta name="twitter:card" content="summary"><meta property="og:image" content="'+e(shareImage)+'"><meta property="og:image:alt" content="'+e(product?.image?product.name:'Logo original FOX GAMER')+'"><link rel="icon" type="image/webp" href="/assets/brand/favicon.webp"><link rel="stylesheet" href="/assets/styles.css"><link rel="stylesheet" href="/assets/brand.css"><script src="/assets/app.js" defer></script><script src="/assets/gallery.js" defer></script>'+extra+'</head><body><a class="skip-link" href="#contenido">Saltar al contenido</a><div class="announcement">Gaming y tecnología en un solo lugar <span>·</span> Envíos a Colombia '+icon('arrow')+'</div><header class="site-header"><nav class="wrap main-nav" aria-label="Navegación principal"><a class="logo" href="/" aria-label="FOX GAMER, inicio"><img class="brand-logo" src="/assets/brand/logo.webp" width="52" height="52" alt=""><span>FOX<span class="logo-light">GAMER</span></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="nav-links">Menú '+icon('menu')+'</button><div class="nav-links" id="nav-links"><a href="/#productos">Catálogo</a><a href="/categorias/consolas/">Consolas</a><a href="/categorias/videojuegos/">Videojuegos</a><a href="/categorias/accesorios/">Accesorios</a><a href="/categorias/apple/">Apple</a></div>'+contact('WhatsApp','Hola FOX GAMER, quiero información sobre sus productos.','nav-contact')+'</nav></header><main id="contenido">'+body+'</main><footer class="footer"><div class="wrap footer-grid"><div><a class="logo" href="/"><img class="brand-logo" src="/assets/brand/logo.webp" width="52" height="52" alt=""><span>FOX<span class="logo-light">GAMER</span></span></a><p>Tu siguiente nivel empieza aquí.<br>Gaming y tecnología en Colombia.</p></div><div><h2>Explora</h2>'+store.categories.map(c=>'<a href="/categorias/'+c.slug+'/">'+e(c.name)+'</a>').join('')+'</div><div><h2>Tu compra</h2><a href="/#condiciones">Condición de los productos</a><a href="/#pagos">Métodos de pago y envíos</a><a href="/#preguntas">Preguntas frecuentes</a><a href="/#contacto">Contacto</a>'+socialLinks+'</div></div><div class="wrap footer-bottom"><span>© '+new Date().getFullYear()+' FOX GAMER</span><span>foxgamer.co · Precios en COP</span></div></footer></body></html>\n';
}
const faq='<section class="section wrap faq" id="preguntas"><p class="eyebrow">ANTES DE COMPRAR</p><h2>Preguntas frecuentes</h2><details><summary>¿Cómo confirmo una compra?</summary><p>Elige un producto y consulta su disponibilidad con FOX GAMER. Antes de pagar, confirma el precio final, la condición, la garantía y los costos de envío. Este sitio no procesa pagos en línea.</p></details><details><summary>¿Qué garantía tiene cada producto?</summary><p>Las condiciones dependen del producto y de la unidad. Consulta la garantía indicada en su ficha y confírmala antes de pagar, junto con el procedimiento de cambios, devoluciones y atención posventa.</p></details><details><summary>¿Puedo financiar mi compra?</summary><p>Hay crédito directo y opciones de financiación según aprobación. Consulta requisitos, plazos y costo total con FOX GAMER.</p></details><details><summary>¿Hacen envíos a mi ciudad?</summary><p>Realizamos envíos nacionales en Colombia con seguimiento. Confirma cobertura, tarifa y fecha estimada para tu dirección antes de completar la compra.</p></details></section>';
await save('index.html',page('FOX GAMER | Videojuegos, consolas, accesorios y Apple','Explora consolas, videojuegos, accesorios y productos Apple en FOX GAMER. Condición visible: Nuevo, Usado o Exhibición. Envíos en Colombia.','/',
'<section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="live-dot"></span> TU MUNDO. TU FORMA DE JUGAR.</p><h1>Sube de nivel.<br><span>Hazlo tuyo.</span></h1><p class="hero-description">Consolas, videojuegos, accesorios y Apple.<br>Todo para jugar, crear y conectar.</p><div class="hero-actions"><a class="button" href="#productos">Explorar catálogo '+icon('arrow')+'</a><a class="text-link" href="#condiciones">Conoce cada condición</a></div><div class="hero-note">'+icon('check')+' Nuevo, Usado o Exhibición. Siempre claro.</div></div><div class="hero-art real-photo"><img src="/assets/photos/img_2452-large.webp" srcset="/assets/photos/img_2452.webp 640w, /assets/photos/img_2452-large.webp 1200w" sizes="(max-width: 760px) 100vw, 48vw" alt="PlayStation 5 fotografiada en la tienda FOX GAMER" width="1200" height="1200" fetchpriority="high"><div class="photo-caption"><span>ASÍ SE VIVE FOX GAMER</span><strong>Tu próximo nivel, de cerca.</strong></div></div></section><div class="benefit-strip"><div class="wrap"><span>'+icon('truck')+' Envíos nacionales</span><span>'+icon('check')+' Condición visible</span><span>'+icon('wallet')+' Opciones de pago</span></div></div><section class="section wrap" id="categorias"><div class="section-top"><div><p class="eyebrow">ELIGE TU UNIVERSO</p><h2>¿Qué estás buscando?</h2></div><a class="text-link" href="#productos">Ir al catálogo '+icon('arrow')+'</a></div><div class="category-grid">'+categoryCards+'</div></section>'+catalog()+gallery()+conditions+payments+faq+contactSection,
'<script type="application/ld+json">'+JSON.stringify({'@context':'https://schema.org','@type':'Organization',name:store.name,url:store.url,logo:store.url+'/assets/brand/fox-gamer-original.jpg',telephone:store.whatsapp?'+'+store.whatsapp:undefined,sameAs:Object.values(store.socials||{}).filter(Boolean)}).replace(/</g,'\\u003c')+'</script>'));
for(const c of store.categories) await save('categorias/'+c.slug+'/index.html',page(c.name+' | FOX GAMER',c.description+' Productos nuevos, usados y de exhibición.','/categorias/'+c.slug+'/', '<section class="wrap category-heading"><nav class="breadcrumbs" aria-label="Ruta de navegación"><a href="/">Inicio</a><span aria-hidden="true">/</span><span>'+e(c.name)+'</span></nav><p class="eyebrow">EL UNIVERSO FOX GAMER</p><h1>'+e(c.name)+'</h1><p class="muted">'+e(c.description)+'</p><div class="category-tabs">'+store.categories.map(x=>'<a '+(x.slug===c.slug?'aria-current="page"':'')+' href="/categorias/'+x.slug+'/">'+e(x.name)+'</a>').join('')+'</div></section>'+catalog(c.slug)+gallery(c.slug)+contactSection));
for(const p of store.products) {
const c=store.categories.find(c=>c.slug===p.category);
const schema={'@context':'https://schema.org','@type':'Product',name:p.name,description:p.description,sku:p.slug,brand:p.brand?{'@type':'Brand',name:p.brand}:undefined,image:p.image?new URL(p.image,store.url).href:undefined};
if(p.price!=null) schema.offers={'@type':'Offer',price:p.price,priceCurrency:'COP',url:store.url+'/productos/'+p.slug+'/',availability:'https://schema.org/'+(p.availability==='available'?'InStock':'OutOfStock'),itemCondition:'https://schema.org/'+(p.condition==='Nuevo'?'NewCondition':'UsedCondition')};
// Unknown availability is intentionally omitted, never represented as preorder.
if(schema.offers && p.availability==='inquiry') delete schema.offers.availability;
await save('productos/'+p.slug+'/index.html',page(p.name+' · '+p.condition+' | FOX GAMER',p.description,'/productos/'+p.slug+'/',
'<section class="wrap section"><nav class="breadcrumbs" aria-label="Ruta de navegación"><a href="/">Inicio</a><span>/</span><a href="/categorias/'+c.slug+'/">'+e(c.name)+'</a><span>/</span><span>'+e(p.name)+'</span></nav><div class="product-detail"><div class="product-visual">'+(p.image?'<img src="'+e(p.image)+'" alt="'+e(p.name)+'" width="800" height="600" fetchpriority="high">':placeholder)+'</div><div><span class="badge">'+e(p.condition)+'</span><p class="eyebrow">'+e(p.brand||c.name)+'</p><h1>'+e(p.name)+'</h1><p>'+e(p.description)+'</p><p class="product-price">'+priceLabel(p)+'</p><p>'+availability[p.availability]+'</p>'+ (p.availability==='soldout'?'<p>Esta unidad no está disponible para compra.</p>':contact('Consultar este producto','Hola FOX GAMER, quiero consultar '+p.name+' ('+p.condition+'). '+store.url+'/productos/'+p.slug+'/'))+'<p class="small">Confirma el precio final y el costo de envío antes de pagar.</p><dl><dt>Estado de la unidad</dt><dd>'+e(p.conditionNotes)+'</dd><dt>Incluye</dt><dd>'+e(p.includes)+'</dd><dt>Garantía</dt><dd>'+e(p.warranty)+'</dd></dl><a class="text-link" href="/#pagos">Ver opciones de pago y envío '+icon('arrow')+'</a></div></div></section>'+conditions,
'<script type="application/ld+json">'+JSON.stringify(schema).replace(/</g,'\\u003c')+'</script>'));
}
await save('404.html',page('Página no encontrada | FOX GAMER','Vuelve al catálogo FOX GAMER.','/404.html','<section class="wrap section empty-state"><p class="eyebrow">ERROR 404</p><h1>No encontramos esta página.</h1><p>Vuelve al inicio para explorar nuestras categorías.</p><a class="button" href="/">Volver al inicio</a></section>','<meta name="robots" content="noindex">'));
await save('robots.txt','User-agent: *\nAllow: /\nSitemap: '+store.url+'/sitemap.xml\n');
await save('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+['/',...store.categories.map(c=>'/categorias/'+c.slug+'/'),...store.products.map(p=>'/productos/'+p.slug+'/')].map(path=>'<url><loc>'+store.url+path+'</loc></url>').join('')+'</urlset>\n');
// Preserve old URLs without leaving obsolete product claims or incorrect photos online.
for(const entry of await readdir('productos',{withFileTypes:true})) {
 if(entry.isDirectory() && !store.products.some(p=>p.slug===entry.name)) await save('productos/'+entry.name+'/index.html',page('Referencia pendiente de actualización | FOX GAMER','Consulta el catálogo actual de FOX GAMER.','/productos/'+entry.name+'/', '<section class="wrap section"><h1>Referencia pendiente de actualización</h1><p>Consulta el catálogo actual o pregunta por esta referencia.</p><a class="button" href="/#productos">Ver catálogo</a>'+contact('Consultar referencia','Hola FOX GAMER, quiero consultar la referencia '+entry.name)+'</section>','<meta name="robots" content="noindex">'));
}
console.log('Generated '+written.length+' files; '+store.products.length+' catalog products.');


