export function customerPages(contact) {
  const help = contact('Escribir a FOX GAMER', 'Hola FOX GAMER, necesito atención sobre mi pedido, garantía o datos personales.');
  const section = (title, content) => `<section class="wrap section customer-policy"><nav class="breadcrumbs" aria-label="Ruta de navegación"><a href="/">Inicio</a><span aria-hidden="true">/</span><span>${title}</span></nav><p class="eyebrow">ATENCIÓN FOX GAMER</p><h1>${title}</h1>${content}${help}</section>`;
  return [
    {path:'/garantia/', title:'Garantía y atención posventa', body:section('Garantía y atención posventa', '<h2>Garantía de consolas</h2><p>Las consolas cuentan con 12 meses de garantía por defectos de fabricación. Conserva el comprobante de compra y el resumen de tu pedido.</p><h2>Otros productos</h2><p>La duración y cobertura aplicables a Apple, accesorios, monitores y videojuegos se detallan en el pedido antes del pago. La condición Nuevo, Usado o Exhibición debe quedar identificada en ese resumen.</p><h2>Cómo solicitar atención</h2><ol><li>Escríbenos por el WhatsApp oficial e indica la referencia de tu pedido.</li><li>Describe la falla y adjunta fotografías o un video cuando sea útil.</li><li>Recibirás las instrucciones para la revisión del producto. Evita intervenirlo antes de recibirlas.</li></ol><p>La reparación o el reemplazo se determina tras la evaluación. Los daños por mal uso o accidentes no están cubiertos por la garantía por defectos de fabricación.</p>')},
    {path:'/cambios-devoluciones/', title:'Cambios y devoluciones', body:section('Cambios y devoluciones', '<h2>Solicita atención sobre tu compra</h2><p>Para reportar un artículo diferente al pedido, un daño, una falla o solicitar un cambio o devolución, escríbenos con el comprobante, la referencia del pedido y una descripción del caso.</p><h2>Recepción y revisión</h2><p>Al recibir el paquete, revisa el artículo y sus accesorios. Si observas alguna novedad, conserva el empaque y envíanos fotografías para facilitar la atención.</p><h2>Antes de devolver un artículo</h2><p>Coordina por WhatsApp la dirección y las instrucciones de devolución. La respuesta dependerá del motivo de la solicitud, el producto y las condiciones de la compra. Las solicitudes de retracto o reversión del pago que correspondan también se atienden por este canal.</p><p>Recibirás por escrito los pasos, los plazos aplicables y, cuando corresponda, la información de reembolso. Esta información de atención no limita los derechos que correspondan al consumidor.</p>')},
    {path:'/privacidad/', title:'Privacidad y uso de datos', body:section('Privacidad y uso de datos', '<h2>Datos para tu pedido</h2><p>El carrito solicita nombre, teléfono, ciudad y, para envío a domicilio, dirección. Estos datos se incluyen en el mensaje que decides enviar a FOX GAMER por WhatsApp para gestionar la compra y la entrega.</p><p>Utilizamos los datos del pedido para la atención, facturación, envío y servicio posventa. Los datos necesarios para la entrega se facilitan al servicio encargado de tu envío.</p><h2>Almacenamiento en tu dispositivo</h2><p>El carrito guarda los artículos seleccionados en tu navegador para que puedas continuar la compra. Los datos de contacto que escribes permanecen en la página mientras preparas el mensaje y no se guardan de forma persistente en el navegador.</p><h2>Medición de interés</h2><p>Registramos clics de compra mediante Netlify: tipo de acción, referencia de producto y página. Esta medición no envía el nombre, teléfono, dirección, texto del pedido ni un identificador de cliente. El proveedor de alojamiento puede procesar información técnica de la conexión.</p><h2>Servicios externos</h2><p>Al abrir WhatsApp, Instagram, Google Maps o un servicio de financiación, se aplican las políticas de ese proveedor. El carrito no solicita contraseñas, datos de tarjetas ni códigos de verificación.</p><h2>Atención sobre tus datos</h2><p>Puedes solicitar información, corrección o eliminación de tus datos mediante el WhatsApp oficial de FOX GAMER. Identifica tu solicitud y el pedido relacionado para que podamos atenderla.</p>')}
  ];
}
