import {escapeHTML as e,priceLabel,whatsappURL} from './catalog.mjs';

export function gameGallery(store){
 const seen=new Set();
 const products=store.products.filter(p=>p.category==='videojuegos'&&p.image&&p.price).filter(p=>{const key=p.name+'|'+p.condition;if(seen.has(key))return false;seen.add(key);return true;});
 const names=new Set(products.map(p=>p.name));
 const featured=['spider-man-2','black-myth-wukong','silent-hill-f','fc-25-ps5','resident-evil-4-ps4','ghost-of-tsushima'];
 products.sort((a,b)=>{const rank=p=>{const i=featured.indexOf(p.slug.replace(/-(nuevo|usado|exhibicion)$/,''));return i<0?99:i;};return rank(a)-rank(b)||a.name.localeCompare(b.name,'es');});
 return `<section class="wrap section game-gallery" id="juegos" aria-labelledby="game-gallery-title">
 <div class="gallery-hero"><div><p class="eyebrow">TU PRÓXIMA PARTIDA EMPIEZA AQUÍ</p><h2 id="game-gallery-title">Elige tu próxima<br><span>aventura.</span></h2><p>Explora nuestras fotos originales, elige tu plataforma y compara precios por condición.</p><div class="gallery-pills"><span>${names.size} títulos fotografiados</span><span>Precios en COP</span><span>Formato físico</span></div></div><a class="gallery-feature" href="/productos/spider-man-2-nuevo/"><img src="/assets/photos/img_6203.webp" alt="Foto original de Marvel’s Spider-Man 2 para PS5" width="560" height="640" fetchpriority="high"><span>Explora. Elige. Juega.</span></a></div>
 <div id="productos"></div><form class="gallery-filters" id="gallery-search" role="search" aria-label="Buscar juegos con foto y precio"><label>Tu próximo juego<input id="gallery-query" type="search" maxlength="100" placeholder="Spider-Man, GTA, Resident Evil…" autocomplete="off"></label><label>Plataforma<select id="gallery-platform"><option value="">PS5 y PS4</option><option>PS5</option><option>PS4</option></select></label><label>Condición<select id="gallery-condition"><option>Nuevo</option><option>Usado</option><option>Exhibición</option></select></label><label>Ordenar<select id="gallery-sort"><option value="featured">Destacados</option><option value="price-asc">Menor precio</option><option value="price-desc">Mayor precio</option><option value="name">Nombre A–Z</option></select></label><button class="button" type="submit">Buscar</button></form>
 <div class="gallery-toolbar"><p id="gallery-count" role="status" aria-live="polite">${names.size} juegos · Nuevo</p><button class="text-button" id="gallery-reset" type="button">Limpiar filtros</button></div>
 <div class="game-gallery-grid" id="gallery-grid">${products.map((p,i)=>`<article class="game-sale" data-game-card data-name="${e(p.name)}" data-platform="${p.name.includes('PS5')?'PS5':'PS4'}" data-condition="${p.condition}" data-price="${p.price}" data-rank="${i}"${p.condition!=='Nuevo'?' hidden':''}><a class="game-sale-photo" href="/productos/${p.slug}/"><img src="${e(p.image)}" alt="${e(p.name)} · fotografía original" width="560" height="640" loading="lazy" decoding="async"><span class="game-platform-badge">${p.name.includes('PS5')?'PS5':'PS4'}</span></a><div class="game-sale-body"><p class="game-sale-meta">Físico · ${e(p.condition)}</p><h3><a href="/productos/${p.slug}/">${e(p.name.replace(/ · PS[45]$/,''))}</a></h3><strong class="game-sale-price">${priceLabel(p)}</strong><p class="game-sale-stock">${p.availability==='soldout'?'Agotado':p.availability==='available'?'Disponible':'Confirma disponibilidad'}</p><a class="button secondary" href="${e(whatsappURL(store.whatsapp,'Hola FOX GAMER, me interesa '+p.name+' en formato físico, condición '+p.condition+', por '+priceLabel(p)+'. Confírmame disponibilidad, idioma, región, contenido y envío.'))}" target="_blank" rel="noopener noreferrer" aria-label="Consultar ${e(p.name+' '+p.condition)} por WhatsApp">Lo quiero · Consultar</a></div></article>`).join('')}</div>
 <div class="gallery-empty" id="gallery-empty" hidden><h3>Busquemos tu próxima aventura</h3><p>Prueba otro título o consulta el directorio de clásicos más abajo.</p><button type="button" class="button secondary" id="gallery-empty-reset">Ver todos los juegos</button></div>
 <div class="load-more-wrap"><button class="button secondary" id="gallery-more" type="button" hidden>Ver más juegos</button></div>
 <p class="small gallery-note">Fotografías del catálogo original de FOX GAMER. Confirma existencias, estado, idioma y región de la unidad antes de comprar. Los códigos y contenidos descargables se verifican por separado.</p>
 </section><link rel="stylesheet" href="/assets/game-gallery.css"><script src="/assets/game-gallery.js" defer></script>`;
}



