import {readFile,writeFile} from 'node:fs/promises';
const path='data/store.json',store=JSON.parse(await readFile(path,'utf8'));
const games=[
 ['fc-25-ps5','EA Sports FC 25 · PS5','IMG_6192'],['black-myth-wukong','Black Myth: Wukong · PS5','IMG_6193'],['ghost-of-tsushima','Ghost of Tsushima · PS5','IMG_6194'],['the-crew-motorfest','The Crew Motorfest · PS5','IMG_6195'],['metal-gear-solid-delta','Metal Gear Solid Delta · PS5','IMG_6196'],['resident-evil-3','Resident Evil 3 · PS5','IMG_6197'],['resident-evil-4','Resident Evil 4 · PS5','IMG_6198'],['elden-ring','Elden Ring · PS5','IMG_6199'],['the-last-of-us-part-i','The Last of Us Part I · PS5','IMG_6200'],['the-last-of-us-part-ii','The Last of Us Part II · PS5','IMG_6201'],['uncharted','Uncharted · PS5','IMG_6202'],['spider-man-2','Marvel’s Spider-Man 2 · PS5','IMG_6203'],['gta-v','Grand Theft Auto V · PS5','IMG_6204'],['ufc-5','EA Sports UFC 5 · PS5','IMG_6205'],['mafia','Mafia · PS5','IMG_6206'],['call-of-duty-black-ops-7','Call of Duty Black Ops 7 · PS5','IMG_6207'],['dragon-ball-sparking-zero','Dragon Ball Sparking! ZERO · PS5','IMG_6208'],['silent-hill-f','Silent Hill f · PS5','IMG_6209'],['little-nightmares-iii','Little Nightmares III · PS5','IMG_6210'],['resident-evil-4-ps4','Resident Evil 4 · PS4','IMG_6268'],['resident-evil-4-ps4-2','Resident Evil 4 · PS4 (unidad 2)','IMG_6269'],['fc-25-ps4','EA Sports FC 25 · PS4','IMG_6492'],['call-of-duty-ps4','Call of Duty · PS4','IMG_6493'],['mud-runner','MudRunner · PS4','IMG_6494'],['mafia-ps4','Mafia · PS4','IMG_6495'],['fc-25-ps4-2','EA Sports FC 25 · PS4 (unidad 2)','IMG_6496'],['efootball','eFootball · PS4','IMG_6497'],['pes','PES · PS4','IMG_6498'],['crash-team-racing','Crash Team Racing · PS4','IMG_6499'],['hello-neighbor','Hello Neighbor · PS4','IMG_6500'],['the-crew-motorfest-ps4','The Crew Motorfest · PS4','IMG_6501'],['minecraft-ps4','Minecraft · PS4','IMG_6502'],['battlefield-v','Battlefield V · PS4','IMG_6503'],['need-for-speed','Need for Speed · PS4','IMG_6508'],['gran-turismo-7','Gran Turismo 7 · PS4','IMG_6510'],['the-last-of-us-ps4','The Last of Us · PS4','IMG_6511'],['the-last-of-us-part-ii-ps4','The Last of Us Part II · PS4','IMG_6512'],['eafc-ps4','EA Sports FC · PS4','IMG_6513'],['cuphead-switch','Cuphead · Nintendo Switch','IMG_6491']
];
const products=[];
for(const [slug,name,image] of games) for(const [condition,suffix,note] of [['Nuevo','nuevo','Producto nuevo; confirma precio y disponibilidad.'],['Exhibición','exhibicion','Unidad de exhibición; revisa señales antes de comprar.'],['Usado','usado','Unidad usada; revisa estado, disco y caja antes de comprar.']]) products.push({slug:`${slug}-${suffix}`,name,description:`${name}. Consulta precio, disponibilidad y contenido con FOX GAMER.`,category:'videojuegos',brand:name.includes('PS5')?'PlayStation':name.includes('PS4')?'PlayStation':'Nintendo',condition,price:null,availability:'inquiry',conditionNotes:note,includes:'Confirma contenido y edición con FOX GAMER.',warranty:'Confirma garantía y condiciones con FOX GAMER.',image:`/assets/photos/${image.toLowerCase()}.webp`,importedGames:true});
store.products=[...store.products.filter(p=>!p.importedGames),...products];
await writeFile(path,JSON.stringify(store,null,2)+'\n');
console.log(`Imported ${products.length} game variants.`);
